### ISSUE TITLE
Initialize ClimaDiagnostics

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaDiagnostics.jl#1]
(WIP)

## Purpose
- formalize / unify current ways of specifying *online* diagnostics and address/identify the missing pieces.
- note that offline diagnostics (postprocessing) and visualization are not part of this SDI. (see https://github.com/CliMA/ClimaCoupler.jl/issues/74 for where this fits in)

## Cost/Benefits/Risks
- b: easier debugging, cleaner comparison with published work, unification of the different ClimaESM repos
- r: this will be a substantial time commitment 

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @charleskawczynski @LenkaNovak 
- Collaborators: @simonbyrne  @trontrytel @yairchn @jiahe23 @sriharshakandala  @szy21 
- Reviewers: TBD (see individual sub-issues)

### Type Tree
- PointwiseKind
- TemporalStatisticKind
  - TimeMeans 
    - MonthlyMean 
  - TimeCovariances (lower priority)
- SpatialStatisticKind
  - HorizontalMean
  - HorizontalCovariances
  - Verticalntegral 
  - GlobalMean
  - ZonalMean (lower priority, infrastructure exists)
  - PressureCoordinates (medium priority, infrastructure does not exist)
  - LatLonGrid (lower priority, infrastructure exists)

### Variable lists
- first pass to include: https://github.com/CliMA/ClimateMachine.jl/issues/214 + energy espectra (e.g., CM , [another example](https://github.com/jswhit/twolevelpe/blob/f92c2c6b8551280d719230653cc4badf6abdea62/plotting/plot_kespectra.py))
- more comprehensive CMIP variable lists: https://github.com/CliMA/ClimaCoupler.jl/issues/74

### Implementation within models
- loosely follow current implementation of diagnostic collection using `TC.jl`:
  - function signatures library: specific to each variable given state or sim [this may be abstracted later]
  - callback: 
    - init
      - reads diagnostics table variable (or list from a .toml file) to get variable Names and Types
      - Initialises object containing:  Names, function signatures, Types, state location
      - calls ClimaDiagnostics.init to create necessary arrays (allocate memory), e.g. for time aggregated fields, fields not in aux
    - calls ClimaDiagnostics.update_diagnostics (see below)

### Implementation within ClimaDiagnostics.update_diagnostics
- this will have access to:
    -  functions general to all models:
        - variable collectors / calculators (given Names, function signatures, Types, states)
        - grid traversers (given Space)
        - pointwise accumulators (given time window)
        - i/o writers (given diagnostics group)
        - coordinate transformations (given source and target coordinates)
        - regridder (given source and target meshes)
    - ...

## Results and deliverables
(Summarize of the key results, deliverables, quality expectations, and performance metrics)
- package including the above components
- use case using Atmos and TC
- inclusion in the AMIP driver (using Atmos, TC, LSM, Coupler, etc.) 

## Task Breakdown And Tentative Due Date (TBD)
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [ ] refine the design above
- [ ] Implement TC-like diagnostics within ClimaAtmos proof of concept
- [ ] Implement a prototype version of ClimaDiagnostics
- [ ] Revisit the above design + get feedback
- [ ] Implement the refined version
- [ ] Broadcast the above to ClimaCoupler
- [ ] Broadcast the above to ClimaLSM

## Proposed Delivery Date
(Your best estimate of the date this software solution will be completed)
